### PR TITLE
Fix Duration parsing

### LINKED ISSUE #34: wrong error parsing duration
Paring `'15:30.0001broken'` gives an error about timezone.

Timezones shouldn't be allowed in durations  at all.

### PR DESCRIPTION
**Pull request by aminalaee**
Fixes https://github.com/pydantic/speedate/issues/34

### CODE REVIEW

**Comment by lig** [comment]
@samuelcolvin this blocks https://github.com/pydantic/speedate/issues/34 which we want for Pydantic V2 Beta 3

File: src/duration.rs [hunk 1]
```diff
@@ -436,13 +436,86 @@ impl Duration {
     }
 
     fn parse_time(bytes: &[u8], offset: usize) -> Result<Self, ParseError> {
-        let t = Time::parse_bytes_offset(bytes, offset)?;
+        if bytes.len() - offset < 5 {
```
Comment (samuelcolvin) [inline src/duration.rs:439]: Looks like this duplicates the logic from `Time::parse_bytes_offset` I think we should have a new method on `TIme`, with signature something like

```rs
pub(crate) fn parse_hms(bytes: &[u8], offset: usize) -> Result<(u8, u8, u8), ParseError> {
```

Which we use both here and in `time.rs`.

**Review by samuelcolvin — COMMENTED** [review]
otherwise idea looks good i think.

File: src/duration.rs (hunk 1 above)
Comment (aminalaee) [reply src/duration.rs:439]: After taking a look, I guess this is not possible because the `length` variable after calculating the `HH:mm:SS...` is needed in `time.rs` in order to get the TzInfo. Otherwise it cannot raise errors for extra characters explicitly.

- We can only have `parse_hm(..)` and parsing second and microsecond should be inlined in both files
- Or change signature to something like `pub(crate) fn parse_partial_time(bytes: &[u8], offset: usize) -> Result<(u8, u8, u8, u32, u8), ParseError> {` to return `HH:mm:SS::fffff` and the length of the parsed bytes to know if optional seconds and microseconds were parsed.

**Comment by samuelcolvin** [comment]
thanks so much.
